backend:
  restart: always
  build: ./backend/
  expose:
    - "8000"
  links:
    - mysql
    - redis
  volumes:
    - ./backend:/usr/src/app
  env_file: .env
  environment:
    DEBUG: 'true'
  command: python manage.py runserver 0.0.0.0:8000

#frontend:
#  restart: always
#  build:
#    ./frontend/web/
#  environment:
#    - HOST=0.0.0.0
#  command:
#    "npm run start"
#  links:
#    - backend

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "800:80"
  volumes:
    - /www/static
    - ./backend:/usr/src/app
  volumes_from:
    - backend
  links:
    - backend
#    - frontend

mysql:
  restart: always
  image: mariadb
  volumes:
    - apuntagol:/var/lib/mysql
  env_file:
    - .env

redis:
  restart: always
  image: redis:latest
  volumes:
    - redisdata:/data

